
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:
  - name: STATIC
    type: "socks5"
    server: "1.1.1.1"
    port: 1080
    username: "user1"
    password: "pass1"
    udp: false

proxy-groups:
  - name: AUTO
    type: select
    proxies:
      - STATIC

rules:
  - MATCH,AUTO
