
mixed-port: 7890
allow-lan: false
mode: rule
log-level: info

proxies:
  - name: STATIC
    type: "http"
    server: "210.245.34.106"
    port: 50562
    username: "aucr"
    password: "b8xl"
    udp: false

proxy-groups:
  - name: AUTO
    type: select
    proxies:
      - STATIC

rules:
  - MATCH,AUTO
